library/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('v1/books/<str:pk>', views.BookAPI.as_view()),
    path('v1/books/', views.book_list, name="books"),
    path('v1/books_create/', views.BookCreate.as_view()),
    path('v1/authors/<str:pk>', views.AuthorApi.as_view()),
    path('v1/authors/', views.author_list, name="authors"),
    path('v1/authors_create/', views.AuthorCreate.as_view()),
    path('v1/orders/<str:pk>', views.OrderAPI.as_view()),
    path('v1/orders/', views.order_list, name="authors"),
    path('v1/orders_create/', views.OrderCreate.as_view())
]

library/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('all_orders', views.all_orders, name='all_orders'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('create_order/', views.create_order, name='create_order'),
    path('close_order/<int:pk>/', views.close_order, name='close_order'),
]

library/order/models.py
from django.db import models, DataError

from authentication.models import CustomUser
from book.models import Book


class Order(models.Model):
    """
           This class represents an Order. \n
           Attributes:
           -----------
           param book: foreign key Book
           type book: ForeignKey
           param user: foreign key CustomUser
           type user: ForeignKey
           param created_at: Describes the date when the order was created. Can't be changed.
           type created_at: int (timestamp)
           param end_at: Describes the actual return date of the book. (`None` if not returned)
           type end_at: int (timestamp)
           param plated_end_at: Describes the planned return period of the book (2 weeks from the moment of creation).
           type plated_end_at: int (timestamp)
       """
    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    end_at = models.DateTimeField(default=None, null=True, blank=True)
    plated_end_at = models.DateTimeField(default=None)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        return f"ORDER ID: {self.pk}, " \
                f"USER ID: {self.user.pk}, " \
                f"BOOK ID: {self.book.pk} " \
            

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    def to_dict(self):
        """
                :return: order id, book id, user id, order created_at, order end_at, order plated_end_at
                :Example:
                | {
                |   'id': 8,
                |   'book': 8,
                |   'user': 8',
                |   'created_at': 1509393504,
                |   'end_at': 1509393504,
                |   'plated_end_at': 1509402866,
                | }
                """
        pass

    @staticmethod
    def create(user, book, plated_end_at):
        orders = Order.objects.all()
        books = set()
        for order in orders:
            if not order.end_at:
                books.add(order.book.id)
        if book.id in books and book.count == 1:
            return None
        try:
            order = Order(user=user, book=book, plated_end_at=plated_end_at)
            order.save()
            return order
        except ValueError:
            return None
        except DataError:
            return None

    @staticmethod
    def get_by_id(order_id):
        try:
            return Order.objects.get(pk=order_id)
        except:
            return None

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at != None:
            self.plated_end_at = plated_end_at
        if end_at != None:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        return list(Order.objects.all())

    @staticmethod
    def get_not_returned_books():
        return Order.objects.filter(end_at=None).values()

    @staticmethod
    def delete_by_id(order_id):
        try:
            a = Order.objects.get(pk=order_id)
        except:
            return False
        else:
            a.delete()
            return True

library/order/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('book', 'user')

library/order/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone
from django.shortcuts import render, redirect
from .forms import OrderForm
from .models import Order

from .models import Order
from book.models import Book


@staff_member_required
def all_orders(request):
    orders = Order.get_all()
    context = {'orders': orders}
    return render(request, 'order/orders_admin.html', context)


@login_required(login_url='login/')
def my_orders(request):
    user = request.user
    orders = Order.objects.filter(user=user)
    context = {'orders': orders}
    return render(request, 'order/orders_user.html', context)


@login_required(login_url='login/')
def create_order(request):
    books = Book.objects.all()
    if request.method == 'POST':
        book_id = request.POST.get('book')
        book = Book.objects.get(id=book_id)
        user = request.user
        plated_end_at = request.POST.get('plated_end_at')
        orders = Order.objects.filter(book=book, end_at=None)
        if book.count == len(orders):
            messages.warning(request, "No available copies of the selected book.")
            return redirect('order:create_order')

        book.count -= 1
        book.save()

        order = Order.create(user=user, book=book, plated_end_at=plated_end_at)
        if order:
            messages.success(request, "Order created successfully.")
            return redirect('order:my_orders')
        else:
            messages.error(request, "Failed to create order.")
            return redirect('order:create_order')
    else:
        context = {'books': books}
        return render(request, 'order/create_order.html', context=context)


@staff_member_required
def close_order(request, pk):
    order = Order.get_by_id(pk)
    if order:
        if request.method == 'POST':
            end_at = timezone.now()
            order.update(end_at=end_at)
            order.save()
            return redirect('order:all_orders')
        else:
            return render(request, 'order/close_order.html', {'order': order})
    else:
        return redirect('order:all_orders')

library/order/templates/order/close_order.html
{% extends 'base.html' %}

{% block content %}
  <h1>Close Order {{ order.pk }}</h1>
  <form method="post">
    {% csrf_token %}
    <label for="end_at">End Date and Time:</label>
    <input type="datetime-local" name="end_at" required>
    <br>
    <button type="submit">Close Order</button>
  </form>
{% endblock %}

library/order/templates/order/create_order.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static "css/create_order.css" %}" />
{% endblock css_files %}

{% block content %}
  <h1>Create an Order</h1>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="book">Book:</label>
      <select name="book" id="book">
        {% for b in books %}
          <option value="{{ b.id }}">{{ b.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="plated_end_at">Planned return date:</label>
      <input type="date" name="plated_end_at" id="plated_end_at" required>
    </div>
    <button type="submit">Create Order</button>
  </form>
{% endblock %}

library/order/templates/order/orders_admin.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static "css/orders_admin.css" %}" />
{% endblock css_files %}

{% block content %}
  <h1>All Orders</h1>
  <table>
    <tr>
      <th>ID</th>
      <th>Book</th>
      <th>User</th>
      <th>Created At</th>
      <th>End At</th>
      <th>Plated End At</th>
      <th>Close Order</th>
    </tr>
    {% for order in orders %}
      <tr>
        <td>{{ order.pk }}</td>
        <td>{{ order.book }}</td>
        <td>{{ order.user }}</td>
        <td>{{ order.created_at }}</td>
        <td>{{ order.end_at }}</td>
        <td>{{ order.plated_end_at }}</td>
        <td><a href="{% url 'order:close_order' order.pk %}">Close Order</a></td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

library/order/templates/order/orders_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block css_files %}
<link rel="stylesheet" href="{% static "css/orders_user.css" %}" />
{% endblock css_files %}
  <h1>My Orders</h1>
  <table>
    <tr>
      <th>ID</th>
      <th>Book</th>
      <th>Created At</th>
      <th>End At</th>
      <th>Plated End At</th>
    </tr>
    {% for order in orders %}
      <tr>
        <td>{{ order.pk }}</td>
        <td>{{ order.book }}</td>
        <td>{{ order.created_at }}</td>
        <td>{{ order.end_at }}</td>
        <td>{{ order.plated_end_at }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}