library/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('v1/books/<str:pk>', views.BookAPI.as_view()),
    path('v1/books/', views.book_list, name="books"),
    path('v1/books_create/', views.BookCreate.as_view()),
    path('v1/authors/<str:pk>', views.AuthorApi.as_view()),
    path('v1/authors/', views.author_list, name="authors"),
    path('v1/authors_create/', views.AuthorCreate.as_view()),
    path('v1/orders/<str:pk>', views.OrderAPI.as_view()),
    path('v1/orders/', views.order_list, name="authors"),
    path('v1/orders_create/', views.OrderCreate.as_view())
]

library/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('all_orders', views.all_orders, name='all_orders'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('create_order/', views.create_order, name='create_order'),
    path('close_order/<int:pk>/', views.close_order, name='close_order'),
]

library/templates/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% block css_files %}{% endblock %}
    {% block title %}<title>{% endblock %}</title>
  </head>
  <body>
    {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
       {{ message }}        
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     </div>
     {% endfor %}
     {% endif %}
    <header>
      <nav>
        <ul>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'order:all_orders' %}">All Orders</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'books' %}">Books</a></li>
            <li><a href="{% url 'order:my_orders' %}">My Orders</a></li>
            <li><a href="{% url 'order:create_order' %}">Create Order</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}{% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>